### PR TITLE
Feature/add status ref2

### PR DESCRIPTION
**Pull request by TA2k**
add alias feature

### CODE REVIEW

**Comment by boellner** [comment]
please check my updates !

**Comment by TA2k** [comment]
I prefer non tab. Because we have so much whitespace left and tabs are easily overseen and not working in dark mode.
Nobody knows XML export without the information the adapter is not usable.
Also a direct link to the migrations guides are the first questions user have. 

Why not showing the user the information on his first screen instead have a lot unused whitespace.

**Comment by boellner** [comment]
I need tab to separate different levels of config.
Only most important configurations are on tab 1 to get the adapter running.
Not eveybody needs to configure alias feature, all this is in tab 2, "hidden" for basic users. 
And I guess there will more features to come that need space to configure.

On top is now a icon "?" that directs to the manual. You could add some extra text or a link as hint to the individual settings, but I would not repeate things of the manual here. eg Windows Program guis would not do this.

**Comment by TA2k** [comment]
For the user connecting act and status are essential not optional. Knx adapter is doing this automatically.
Every user will ask for this. There is no reason to hide the feature. There is no reason to make a bad ui because maybe in the future more feature comes eventually.

The idea is the user wants to use the adapter, the user has to figure what the ? means. Then click on scroll down on the right point to figure out was ETS XML means and then can start to user the adapter?

Windows Program GUIs are not good UI and should not be copy. The user should able to use a tool intuitive without finding the readme and then read the complete readme. 

It makes sense to repeat manuals on the point when the user need it and not say find the ? and figure it out by ourself.

**Comment by boellner** [comment]
for me it is optional, I dont have this use case and knx adapter does this only for the rare cases where two are matching
and for somebody who is using the adapter for the first time and wants to play around gets overwhelmed by the options. Hiding information is the better approach than extensively explain, users can experience new features over time

You can add additional hints for every setting, but repeating the manual is not a good practive and will get out of sync soon and i also dont see it in any professional modern ui (android, ios..)

**Comment by TA2k** [comment]
But because it is for you optional this should be not the reference. 
Im not sure how you make your vis with knx objects. But every user will have the issue. This is not an optional step this is step 2 of the import.

How to create a export xml and migrate from knx.0 is not a thing user can experience overtime. 
The user will see a button a the first start and will not know how he can play around.

Explaining exporting and XML File and a link to the migrate guide will never go out of sync.

And Settings page is not an iOS App normally have iOS Apps an interactive tutorial. 
They are not showing a Button and Question mark and 200 line of readme.

**Comment by boellner** [comment]
A first time user does not know how to fill out a regexp that is matching his project and would also not know how prepare his knx project with this little info ....
It needs a chapter in the manual, gui should give some hints. You can add this later on, but now we have to proceed. And tabs are needed to be extensible for future features that come for sure and then not overload the onepage layout

**Comment by TA2k** [comment]
Tabs should be introduce when it is needed and not because they maybe needed in the future

**Pull request merged**
