### PR TITLE
add alias alternative

### PR DESCRIPTION
**Pull request by TA2k**
Please allow the user to use knx adapter way as an alternative to alias to prevent a lot of work.
Marked as deprecated but this will save a lot of time for migrating existing systems.
Please consider the user needs not your personal opinion

### CODE REVIEW

**Comment by boellner** [comment]
but why , 
its a new system, it is explicitly not compatible with any existing one, users will have to migrate
i dont want to maintain the overhead of two approaches with the risk that things get mixed up and getting error reports not knowing what setup and so on...

**Comment by TA2k** [comment]
The system is different but migrated scripts and vis are the same and basing on this kind of connection.
This is marked as deprecated and the user receive a warning to use alias and not receive supports/maintenance
You will receive all the time error reports without knowing the setup this is not a critical change of the system

**Comment by boellner** [comment]
the only use would be to inform the user that his setup is deprcated. The work is still to be done. You better describe this in the migration documentation

**Comment by TA2k** [comment]
But the user can decide when he move to aliases. 
You can remove this feature at any time if your receive error report or it cause any issue.
When I add a migration comment you will merge the feature?

**Comment by boellner** [comment]
no I dont want this feature, please accept this

**Comment by TA2k** [comment]
But I need this feature. Is there are review reason or a bug in the code?
Or is this only a your personal preference how you create you private system?

**Comment by boellner** [comment]
But it is already deprecated and would be thrown out anyway, I do not see the argument why releasing a feature that is thrown out soon with all the  confusion it will creats

**Comment by TA2k** [comment]
Because I don't want to use aliases and don't see a need for aliases. 

Deprecated means it will not maintained in the future and removed if you are right and this causes issue in the future. I don't see at the moment no reason to remove it in the future

**Pull request closed without merging**
