### PR TITLE
allow no DPT import and controling

### PR DESCRIPTION
**Pull request by TA2k**
https://github.com/iobroker-community-adapters/ioBroker.openknx/issues/79

### CODE REVIEW

**Comment by TA2k** [comment]
@boellner Are we allowed to add this feature? Or you don't want it for your setup?

**Comment by boellner** [comment]
lets await the discussion, but providing raw interfaces is of not much benefit

**Comment by TA2k** [comment]
I cannot judge about the benefit for each user. It is up to the user to use a raw interface I will not limit the user because of personal preference

**Comment by boellner** [comment]
The user has a problem with not generated objects because of missing dpt information in the ETS4 exchange file.
Whith this option he has the object but still does not know the datatype.
So he has to implement this in his application logic. He could have it easier by working on the exchange file.
This change is not solving anyones existing problem, making everything configurable without broader uses cases makes the software hard to maintain for little benefit and complicated settings lower user acceptance

**Comment by TA2k** [comment]
Why harder to maintain? 
The adapter already has implemented raw read and write of unknown DPT. 
This change will only allow to import no DPT as Unknown If the user request this explicitly
Please point exactly the change which is hard to maintain in the future.

I'm not able to judge the problems of users, it solving the problem of user which are not able to update to ETS5 and still after updating they need to add all DPT manually. 
I don't see how this checkbox makes the software harder to maintain or to complicated for the user.

**Comment by boellner** [comment]
adding this is leaving to messed up installation. user has to cleanup his config, the adapter does not solve each little problem if there are better ways

**Pull request closed without merging**
